(() => {
  const $ = (s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const state={stats:null,leads:[],prospects:[]};
  const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const api=async(url,opt={})=>{const r=await fetch(url,opt);if(r.status===401){location.href='/admin/login';throw new Error('401')}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Błąd');return d};

  async function init(){try{const me=await api('/api/admin/me');$('#admin-email').textContent=me.email;await Promise.all([loadStats(),loadLeads(),loadProspects()])}catch(e){if(e.message!=='401')console.error(e)}}

  $$('.side-nav button').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.view;$$('.side-nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$('#view-title').textContent={dashboard:'Dashboard',leads:'Leady',prospects:'Firmy / Prospecting',help:'Konfiguracja'}[v]||v}));
  $('#logout').addEventListener('click',async()=>{await fetch('/api/admin/logout',{method:'POST'});location.href='/admin/login'});
  $('#refresh').addEventListener('click',()=>Promise.all([loadStats(),loadLeads(),loadProspects()]));

  async function loadStats(){const d=state.stats=await api('/api/admin/stats');$('#m-today').textContent=d.today.visitors||0;$('#m-7').textContent=d.d7.visitors||0;$('#m-30').textContent=d.d30.pageviews||0;$('#m-conv').textContent=`${d.conversion||0}%`;drawChart(d.series||[]);bars('#sources',d.sources,'source','visitors');bars('#top-pages',d.topPages,'path','pageviews');bars('#devices',d.devices,'device','visitors')}
  function bars(sel,rows,labelKey,valueKey){const el=$(sel),max=Math.max(1,...rows.map(r=>Number(r[valueKey]||0)));el.innerHTML=rows.length?rows.map(r=>`<div class="bar-row"><span>${esc(r[labelKey]||'—')}</span><div class="bar"><i style="width:${Math.max(3,Math.round(Number(r[valueKey]||0)/max*100))}%"></i></div><strong>${Number(r[valueKey]||0)}</strong></div>`).join(''):'<span class="muted">Brak danych.</span>'}
  function drawChart(rows){const c=$('#traffic-chart'),ctx=c.getContext('2d'),box=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=box.width*dpr;c.height=box.height*dpr;ctx.scale(dpr,dpr);const w=box.width,h=box.height,p=30;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#e5e5e2';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=p+(h-2*p)*i/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}if(!rows.length)return;const max=Math.max(1,...rows.map(r=>Number(r.pageviews||0)));ctx.strokeStyle='#111';ctx.lineWidth=2.2;ctx.beginPath();rows.forEach((r,i)=>{const x=p+(w-2*p)*(i/(Math.max(1,rows.length-1))),y=h-p-(h-2*p)*(Number(r.pageviews||0)/max);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#777';ctx.font='10px sans-serif';ctx.fillText(rows[0]?.day||'',p,h-8);ctx.textAlign='right';ctx.fillText(rows.at(-1)?.day||'',w-p,h-8);ctx.textAlign='left'}
  addEventListener('resize',()=>state.stats&&drawChart(state.stats.series||[]));

  $('#lead-filter').addEventListener('click',loadLeads);$('#lead-q').addEventListener('keydown',e=>e.key==='Enter'&&loadLeads());
  async function loadLeads(){const q=encodeURIComponent($('#lead-q')?.value||''),status=encodeURIComponent($('#lead-status')?.value||'all');state.leads=await api(`/api/admin/leads?q=${q}&status=${status}`);renderLeads()}
  function renderLeads(){const body=$('#leads-body');body.innerHTML=state.leads.length?state.leads.map(l=>`<tr><td>${esc((l.created_at||'').replace('T',' '))}</td><td><b>${esc(l.company||l.name)}</b><br><span class="muted">${esc(l.company?l.name:'')}</span></td><td><a href="mailto:${esc(l.email)}">${esc(l.email)}</a><br>${esc(l.phone||'')}</td><td>${esc(l.service||'—')}<br><span class="muted">${esc(l.budget||'')}</span></td><td>${esc(l.source||'direct')}</td><td><select class="select lead-status-change" data-id="${l.id}">${['nowy','kontakt','oferta','follow-up','wygrany','przegrany'].map(s=>`<option ${s===l.status?'selected':''}>${s}</option>`).join('')}</select></td><td><input class="input lead-follow" type="date" data-id="${l.id}" value="${esc((l.follow_up_at||'').slice(0,10))}"></td><td><button class="btn small lead-open" data-id="${l.id}">Otwórz</button></td></tr>`).join(''):'<tr><td colspan="8" class="muted">Brak leadów.</td></tr>';
    $$('.lead-status-change').forEach(x=>x.addEventListener('change',()=>updateLead(x.dataset.id,{status:x.value})));$$('.lead-follow').forEach(x=>x.addEventListener('change',()=>updateLead(x.dataset.id,{followUpAt:x.value||null})));$$('.lead-open').forEach(x=>x.addEventListener('click',()=>openLead(Number(x.dataset.id))))}
  async function updateLead(id,data){await api(`/api/admin/leads/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});await loadLeads()}
  async function openLead(id){const l=state.leads.find(x=>x.id===id);if(!l)return;const notes=await api(`/api/admin/leads/${id}/notes`);$('#lead-detail').innerHTML=`<h2>${esc(l.company||l.name)}</h2><p class="muted">${esc(l.name)}</p><div class="kv"><span>E-mail</span><b>${esc(l.email)}</b></div><div class="kv"><span>Telefon</span><b>${esc(l.phone||'—')}</b></div><div class="kv"><span>Usługa</span><b>${esc(l.service||'—')}</b></div><div class="kv"><span>Budżet</span><b>${esc(l.budget||'—')}</b></div><div class="kv"><span>Źródło</span><b>${esc(l.source||'direct')}</b></div><div class="kv"><span>Landing</span><b>${esc(l.page_path||'—')}</b></div><h3>Wiadomość</h3><p>${esc(l.message)}</p><div class="notes"><h3>Notatki</h3><div class="notes-list">${notes.length?notes.map(n=>`<div class="note">${esc(n.note)}<br><small class="muted">${esc(n.created_at)}</small></div>`).join(''):'<span class="muted">Brak notatek.</span>'}</div><textarea class="textarea" id="new-note" placeholder="Dodaj notatkę" style="width:100%;min-height:90px"></textarea><button class="btn dark" id="save-note" data-id="${id}" style="margin-top:8px">Zapisz notatkę</button></div>`;$('#lead-drawer').classList.add('open');$('#save-note').addEventListener('click',async e=>{const note=$('#new-note').value.trim();if(!note)return;await api(`/api/admin/leads/${id}/notes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note})});openLead(id)})}
  $('[data-close-drawer]').addEventListener('click',()=>$('#lead-drawer').classList.remove('open'));

  $('#p-add').addEventListener('click',async()=>{const domain=$('#p-domain').value.trim();if(!domain)return alert('Podaj domenę.');await api('/api/admin/prospects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company:$('#p-company').value,domain,city:$('#p-city').value,email:$('#p-email').value})});['#p-company','#p-domain','#p-city','#p-email'].forEach(s=>$(s).value='');loadProspects()});
  $('#p-filter').addEventListener('click',loadProspects);$('#p-q').addEventListener('keydown',e=>e.key==='Enter'&&loadProspects());
  async function loadProspects(){const q=encodeURIComponent($('#p-q')?.value||''),old=$('#p-old')?.checked?'1':'0',noSeo=$('#p-noseo')?.checked?'1':'0';state.prospects=await api(`/api/admin/prospects?q=${q}&old=${old}&noSeo=${noSeo}`);renderProspects()}
  function renderProspects(){const body=$('#prospects-body');body.innerHTML=state.prospects.length?state.prospects.map(p=>{let issues=[];try{issues=JSON.parse(p.issues_json||'[]')}catch{}const sc=Number(p.score||0),cl=sc>=50?'high':sc>=25?'mid':'low';return `<tr><td><b>${esc(p.company||'—')}</b><br><span class="muted">${esc(p.industry||'')}</span></td><td><a href="${esc(/^https?:/.test(p.domain)?p.domain:'https://'+p.domain)}" target="_blank" rel="noopener">${esc(p.domain)} ↗</a><br><span class="muted">${esc(p.email||'')}</span></td><td>${esc(p.city||'—')}</td><td>${p.footer_year||'—'}</td><td><span class="score ${cl}">${sc}</span></td><td class="issues">${issues.slice(0,2).map(esc).join('<br>')||'Nie analizowano'}</td><td><select class="select p-status" data-id="${p.id}">${['nowy','do kontaktu','kontakt','follow-up','wygrany','odrzucony'].map(s=>`<option ${s===p.status?'selected':''}>${s}</option>`).join('')}</select></td><td><input class="input p-follow" type="date" data-id="${p.id}" value="${esc((p.follow_up_at||'').slice(0,10))}"></td><td><div class="toolbar" style="margin:0"><button class="btn small p-check" data-id="${p.id}">Sprawdź</button><button class="btn small p-draft" data-id="${p.id}">Mail</button>${p.email?`<button class="btn small p-copy" data-email="${esc(p.email)}">Kopiuj e-mail</button>`:''}</div></td></tr>`}).join(''):'<tr><td colspan="8" class="muted">Brak firm.</td></tr>';
    $$('.p-check').forEach(b=>b.addEventListener('click',async()=>{const old=b.textContent;b.textContent='Analiza…';b.disabled=true;try{const d=await api(`/api/admin/prospects/${b.dataset.id}/check`,{method:'POST'});alert(`Score: ${d.score}\nStopka: ${d.footerYear||'brak'}\n\n${d.issues.join('\n')}`);await loadProspects()}catch(e){alert(e.message)}finally{b.textContent=old;b.disabled=false}}));$$('.p-draft').forEach(b=>b.addEventListener('click',async()=>{const d=await api(`/api/admin/prospects/${b.dataset.id}/draft-email`,{method:'POST'});$('#draft-subject').value=d.subject;$('#draft-body').value=d.draft;$('#email-modal').classList.add('open')}));$$('.p-copy').forEach(b=>b.addEventListener('click',()=>navigator.clipboard.writeText(b.dataset.email)));$$('.p-status').forEach(x=>x.addEventListener('change',()=>api(`/api/admin/prospects/${x.dataset.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:x.value})})));$$('.p-follow').forEach(x=>x.addEventListener('change',()=>api(`/api/admin/prospects/${x.dataset.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({followUpAt:x.value||null})}))) }


  $('#p-check-visible').addEventListener('click', async () => {
    const btn=$('#p-check-visible'), original=btn.textContent; btn.disabled=true;
    const ids=state.prospects.slice(0,25).map(p=>p.id);
    for(let i=0;i<ids.length;i++){
      btn.textContent=`Analiza ${i+1}/${ids.length}`;
      try{ await api(`/api/admin/prospects/${ids[i]}/check`,{method:'POST'}); }catch(e){ console.warn('Błąd analizy',ids[i],e.message); }
      await new Promise(r=>setTimeout(r,1200));
    }
    btn.textContent=original;btn.disabled=false;await loadProspects();
  });

  $('#close-modal').addEventListener('click',()=>$('#email-modal').classList.remove('open'));$('#copy-draft').addEventListener('click',async()=>{await navigator.clipboard.writeText(`Temat: ${$('#draft-subject').value}\n\n${$('#draft-body').value}`);$('#copy-draft').textContent='Skopiowano';setTimeout(()=>$('#copy-draft').textContent='Kopiuj',1200)});

  $('#csv-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const txt=await file.text();const rows=parseCsv(txt);$('#import-status').textContent=`Wczytano ${rows.length} wierszy…`;try{const d=await api('/api/admin/prospects/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows})});$('#import-status').textContent=`Zaimportowano: ${d.imported}`;loadProspects()}catch(err){$('#import-status').textContent=err.message}e.target.value=''});
  function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const parse=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===sep&&!q){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out};const headers=parse(lines.shift()).map(h=>h.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_'));return lines.map(line=>{const vals=parse(line),o={};headers.forEach((h,i)=>o[h]=vals[i]||'');o.company=o.company||o.firma||o.nazwa_firmy;o.domain=o.domain||o.www||o.url||o.strona;o.city=o.city||o.miasto;o.phone=o.phone||o.telefon;o.source=o.source||o.zrodlo;o.notes=o.notes||o.notatki;return o}).filter(r=>r.domain)}

  init();
})();
