const projects=[
{name:'DRG Auto',sector:'Motoryzacja / detailing',desktop:'drg-desktop.webp',mobile:'drg-mobile.webp',href:'https://jakubskrzypiec.github.io/drgauto/',summary:'Strona, która łączy sprzedaż samochodów z ofertą detailingu i prowadzi prosto do telefonu.',challenge:'Dwie różne usługi musiały działać jako jedna spójna marka.',result:'Mocny pierwszy ekran, krótka ścieżka do oferty i wygodny kontakt na telefonie.',tags:['UX/UI','WDROŻENIE','MOBILE']},
{name:'Pani Projekt',sector:'Projektowanie wnętrz',desktop:'pani-projekt-desktop.webp',mobile:'pani-projekt-mobile.webp',href:'https://jakubskrzypiec.github.io/paniprojekt/',summary:'Edytorialna strona dla studia wnętrz, która sprzedaje jakością realizacji, nie nadmiarem tekstu.',challenge:'Pokazać premium charakter marki bez przeładowania interfejsu.',result:'Spokojna hierarchia, duże kadry i czytelna droga do zapytania.',tags:['PROJEKT','FRONT-END','RWD']},
{name:'Maciejewska Design',sector:'Architektura wnętrz',desktop:'maciejewska-desktop.webp',mobile:'maciejewska-mobile.webp',href:'https://jakubskrzypiec.github.io/maciejewskadesign/',summary:'Minimalistyczne portfolio, w którym realizacje grają pierwszoplanową rolę.',challenge:'Utrzymać klasę dużych zdjęć również na małym ekranie.',result:'Oszczędny interfejs, precyzyjna typografia i dopracowany mobile.',tags:['DESIGN','PORTFOLIO','MOBILE']},
{name:'Werka Bramy',sector:'Usługi lokalne',desktop:'werka-desktop.webp',mobile:'werka-mobile.webp',href:'https://jakubskrzypiec.github.io/werkabramy/',summary:'Sprzedażowy landing page dla lokalnej firmy wykonującej bramy i ogrodzenia.',challenge:'W kilka sekund wyjaśnić zakres, obszar działania i przewagę oferty.',result:'Jednoznaczny komunikat, lokalne frazy i szybka bezpłatna wycena.',tags:['LANDING PAGE','COPY','LOCAL SEO']}];
const list=document.querySelector('#project-list');list.innerHTML=projects.map((p,i)=>`<article class="project reveal ${i%2?'reverse':''}"><div class="project-media"><div class="slant-frame"><img src="${p.desktop}" alt="${p.name} — widok desktop" loading="lazy"></div><div class="slant-phone"><div><img src="${p.mobile}" alt="${p.name} — widok mobilny" loading="lazy"></div><span></span></div><b>0${i+1}</b></div><div class="project-copy"><div class="project-top"><span>0${i+1} / 04</span><span>${p.sector}</span></div><small>REALIZACJA</small><h3>${p.name}</h3><p class="project-summary">${p.summary}</p><div class="project-case"><div><small>WYZWANIE</small><p>${p.challenge}</p></div><div><small>EFEKT</small><p>${p.result}</p></div></div><div class="project-tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><a href="${p.href}" target="_blank" rel="noreferrer">Zobacz stronę <span>↗</span></a></div></article>`).join('');
const menu=document.querySelector('.menu'),nav=document.querySelector('.nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.classList.toggle('active',open);menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Zamknij menu':'Otwórz menu')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.classList.remove('active')}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('visible')),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelector('.hero-scene').addEventListener('mousemove',e=>{if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;e.currentTarget.style.setProperty('--scene-x',`${x*8}px`);e.currentTarget.style.setProperty('--scene-y',`${y*5}px`)});
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),s=`Zapytanie 21project — ${d.get('service')}`,b=[`Imię / firma: ${d.get('name')}`,`E-mail: ${d.get('email')}`,`Telefon: ${d.get('phone')||'nie podano'}`,`Usługa: ${d.get('service')}`,'',d.get('message')].join('\n');location.href=`mailto:jakubskrzypiec.dev@gmail.com?subject=${encodeURIComponent(s)}&body=${encodeURIComponent(b)}`});
